config/routes.rb
Rails.application.routes.draw do
  resources :exercicios
  resources :instrutors
  resources :academia
  resources :alunos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :proprietarios, :controllers => {:registrations => "registrations"}

end

app/controllers/academia_controller.rb
class AcademiaController < ApplicationController
  before_action :set_academium, only: %i[ show edit update destroy ]

  # GET /academia or /academia.json
  def index
    @academia = Academium.all
  end

  # GET /academia/1 or /academia/1.json
  def show
  end

  # GET /academia/new
  def new
    @academium = Academium.new
    @proprietarios = Proprietario.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }
    @academium.build_endereco
  end

  # GET /academia/1/edit
  def edit
    @proprietarios = Proprietario.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }
  end

  # POST /academia or /academia.json
  def create
    @academium = Academium.new(academium_params)
    @proprietarios = Proprietario.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }
    @academium.endereco = Endereco.new(academium_params[:endereco_attributes])

    respond_to do |format|
      if @academium.save
        format.html { redirect_to academium_url(@academium), notice: "Academium was successfully created." }
        format.json { render :show, status: :created, location: @academium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @academium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academia/1 or /academia/1.json
  def update
    @proprietarios = Proprietario.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }

    respond_to do |format|
      if @academium.update(academium_params)
        format.html { redirect_to academium_url(@academium), notice: "Academium was successfully updated." }
        format.json { render :show, status: :ok, location: @academium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @academium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academia/1 or /academia/1.json
  def destroy
    @academium.destroy

    respond_to do |format|
      format.html { redirect_to academia_url, notice: "Academium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_academium
      @academium = Academium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def academium_params
      params.require(:academium).permit(:nome, :email_comercial, :cnpj, :contato_comercial, :ativo, :proprietario_id,
                                        endereco_attributes: [:logradouro, :cep])
    end
end

app/helpers/academia_helper.rb
module AcademiaHelper
end

app/views/academia/_academium.html.erb
<div id="<%= dom_id academium %>">
  <p>
    <strong>Nome:</strong>
    <%= academium.nome %>
  </p>

  <p>
    <strong>Email Comercial:</strong>
    <%= academium.email_comercial %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= academium.endereco.logradouro %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= academium.endereco.cep %>
  </p>

  <p>
    <strong>Cnpj:</strong>
    <%= academium.cnpj %>
  </p>

  <p>
    <strong>Contato Comercial:</strong>
    <%= academium.contato_comercial %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= academium.ativo %>
  </p>

  <p>
    <strong>Proprietario:</strong>
    <%= academium.proprietario.nome %>
  </p>

</div>

app/views/academia/_form.html.erb
<%= form_with(model: academium) do |form| %>
  <% if academium.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(academium.errors.count, "error") %> prohibited this academium from being saved:</h2>

      <ul>
        <% academium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :email_comercial, style: "display: block" %>
    <%= form.text_field :email_comercial %>
  </div>

  <%= form.fields_for :endereco do |endereco_form| %>
    <div>
      <%= endereco_form.label :logradouro, display: "block" %>
      <%= endereco_form.text_field :logradouro %>
    </div>

    <div>
      <%= endereco_form.label :cep, display: "block" %>
      <%= endereco_form.text_field :cep %>
    </div>

  <%end %>

  <div>
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div>
    <%= form.label :contato_comercial, style: "display: block" %>
    <%= form.text_field :contato_comercial %>
  </div>

  <div>
    <%= form.label :ativo, style: "display: block" %>
    <%= form.check_box :ativo %>
  </div>

  <div class="col-md-6 form-group">
    <%= form.label :proprietario_id, "Proprietário", style: "display: block" %>
    <%= form.select :proprietario_id, @proprietarios, {}, { class: "form-select" } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/academia/edit.html.erb
<h1>Editing academium</h1>

<%= render "form", academium: @academium %>

<br>

<div>
  <%= link_to "Show this academium", @academium %> |
  <%= link_to "Back to academia", academia_path %>
</div>

app/views/academia/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Academia</h1>

<%= link_to "Voltar para a home", "/" %>

<div id="academia">
  <% @academia.each do |academium| %>
    <%= render academium %>
    <p>
      <%= link_to "Show this academium", academium %>
    </p>
  <% end %>
</div>

<div>
  <br>
  <a href="/exercicios/new">criar novo exercicio</a>
  <a href="/exercicios">seus exercicios</a>
</div>


<br>

<%= link_to "nova academia", new_academium_path %>

app/views/academia/new.html.erb
<h1>New academium</h1>

<%= render "form", academium: @academium %>

<br>

<div>
  <%= link_to "Voltar para a home", "/" %>
</div>

app/views/academia/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @academium %>

<div>
  <%= link_to "Editar", edit_academium_path(@academium) %> |
  <%= link_to "Voltar para todas as academias", academia_path %>

  <%= button_to "Deletar", @academium, method: :delete %>
</div>