config/routes.rb
Rails.application.routes.draw do
  resources :exercicios
  resources :instrutors
  resources :academia
  resources :alunos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :proprietarios, :controllers => {:registrations => "registrations"}

end

app/models/exercicio.rb
class Exercicio < ApplicationRecord
  belongs_to :academium
  validates :titulo, presence: true, length: { minimum: 5 },format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :dificuldade, presence: true
  validates :calorias, presence: true, numericality: { only_integer: true }, length: { minimum: 1 }
  validates :descricao, presence: true, length: { minimum: 10}, length: { maximum: 500 }, format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :quantidade, presence: true, numericality: { only_integer: true }, length: { minimum: 1 }
  validates :tipo, presence: true, length: { minimum: 5 }, format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :academium_id, presence: true
  
end

app/controllers/exercicios_controller.rb
class ExerciciosController < ApplicationController
  before_action :set_exercicio, only: %i[ show edit update destroy ]

  # GET /exercicios or /exercicios.json
  def index
    @exercicios = Exercicio.all
  end

  # GET /exercicios/1 or /exercicios/1.json
  def show
  end

  # GET /exercicios/new
  def new
    @exercicio = Exercicio.new
    @academias = Academium.all.map { |acad| ["#{acad.id} - #{acad.nome}", acad.id] }
    @dificuldes = ["Fácil", "Médio", "Difícil"]
  end

  # GET /exercicios/1/edit
  def edit
    @academias = Academium.all.map { |acad| ["#{acad.id} - #{acad.nome}", acad.id] }
    @dificuldes = ["Fácil", "Médio", "Difícil"]
  end

  # POST /exercicios or /exercicios.json
  def create
    @exercicio = Exercicio.new(exercicio_params)
    @academias = Academium.all.map { |acad| ["#{acad.id} - #{acad.nome}", acad.id] }
    @dificuldes = ["Fácil", "Médio", "Difícil"]

    respond_to do |format|
      if @exercicio.save
        format.html { redirect_to exercicio_url(@exercicio), notice: "Exercicio was successfully created." }
        format.json { render :show, status: :created, location: @exercicio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercicios/1 or /exercicios/1.json
  def update
    respond_to do |format|
      if @exercicio.update(exercicio_params)
        format.html { redirect_to exercicio_url(@exercicio), notice: "Exercicio was successfully updated." }
        format.json { render :show, status: :ok, location: @exercicio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercicios/1 or /exercicios/1.json
  def destroy
    @exercicio.destroy

    respond_to do |format|
      format.html { redirect_to exercicios_url, notice: "Exercicio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercicio
      @exercicio = Exercicio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercicio_params
      params.require(:exercicio).permit(:titulo, :dificuldade, :calorias, :descricao, :quantidade, :tipo, :academium_id)
    end
end

app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

app/views/exercicios/_exercicio.html.erb
<div id="<%= dom_id exercicio %>">
  <p>
    <strong>Titulo:</strong>
    <%= exercicio.titulo %>
  </p>

  <p>
    <strong>Dificuldade:</strong>
    <%= exercicio.dificuldade %>
  </p>

  <p>
    <strong>Calorias:</strong>
    <%= exercicio.calorias %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= exercicio.descricao %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= exercicio.quantidade %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= exercicio.tipo %>
  </p>

  <p>
    <strong>Academium:</strong>
    <%= exercicio.academium.nome %>
  </p>

</div>

app/views/exercicios/_form.html.erb
<%= form_with(model: exercicio) do |form| %>
  <% if exercicio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercicio.errors.count, "error") %> prohibited this exercicio from being saved:</h2>

      <ul>
        <% exercicio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :dificuldade, style: "display: block" %>
    <%= form.select :dificuldade,  @dificuldes, {}, { class: "form-select" }%>
  </div>

  <div>
    <%= form.label :calorias, style: "display: block" %>
    <%= form.text_field :calorias %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>

  <div>
    <%= form.label :academium_id, style: "display: block" %>
    <%= form.select :academium_id, @academias, {}, { class: "form-select" } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exercicios/edit.html.erb
<h1>Editing exercicio</h1>

<%= render "form", exercicio: @exercicio %>

<br>

<div>
  <%= link_to "Show this exercicio", @exercicio %> |
  <%= link_to "Back to exercicios", exercicios_path %>
</div>

app/views/exercicios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Exercicios</h1>

<%= link_to "Voltar para a home", "/" %>

<div id="exercicios">
  <% @exercicios.each do |exercicio| %>
    <%= render exercicio %>
    <p>
      <%= link_to "Show this exercicio", exercicio %>
    </p>
  <% end %>
</div>

<br>

<%= link_to "Novo exercicio", new_exercicio_path %>

app/views/exercicios/new.html.erb
<h1>New exercicio</h1>

<%= render "form", exercicio: @exercicio %>

<br>

<div>
  <%= link_to "Voltar para a home", "/" %>
</div>

app/views/exercicios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exercicio %>

<div>
  <%= link_to "Editar", edit_exercicio_path(@exercicio) %> |
  <%= link_to "Voltar para todos os exercícios", exercicios_path %>

  <%= button_to "Deletar", @exercicio, method: :delete %>
</div>