config/routes.rb
Rails.application.routes.draw do
  resources :exercicios
  resources :instrutors
  resources :academia
  resources :alunos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :proprietarios, :controllers => {:registrations => "registrations"}

end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :academium
  has_one :endereco, dependent: :destroy
  accepts_nested_attributes_for :endereco, allow_destroy: true

  validates :nome, presence: true, length: { maximum: 100, minimum: 10 }, format: { with: /\A[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+\z/, message: "Somente letras"}
  validates :cpf, presence: true, length: { is: 11 }, uniqueness: true, format: { with: /\A[0-9]+\z/, message: "Somente números" }
  validates :data_nascimento, presence: true, comparison: {less_than: Time.zone.today, greater_than: Date.new(1850, 1, 1)}
  validates :contato, presence: true, length: { is: 11 }, format: { with: /\A[0-9]+\z/, message: "Somente números" }
  validates :senha , presence: true, length: { maximum: 100, minimum: 8 }

end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1 or /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
    @academias = Academium.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }
    @aluno.build_endereco
  end

  # GET /alunos/1/edit
  def edit
    @academias = Academium.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }
  end

  # POST /alunos or /alunos.json
  def create
    @academias = Academium.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }
    @aluno = Aluno.new(aluno_params)
    @aluno.endereco = Endereco.new(aluno_params[:endereco_attributes])

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    @academias = Academium.all.map { |prop| ["#{prop.id} - #{prop.nome}", prop.id] }
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @aluno.destroy

    respond_to do |format|
      format.html { redirect_to alunos_url, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:nome, :cpf, :data_nascimento, :contato, :senha, :academium_id,
                                    endereco_attributes: [:logradouro, :cep])
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_aluno.html.erb
<div id="<%= dom_id aluno %>">
  <p>
    <strong>Nome:</strong>
    <%= aluno.nome %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= aluno.endereco.logradouro %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= aluno.endereco.cep %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= aluno.cpf %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= aluno.data_nascimento %>
  </p>

  <p>
    <strong>Contato:</strong>
    <%= aluno.contato %>
  </p>

</div>

app/views/alunos/_form.html.erb
<%= form_with(model: aluno) do |form| %>
  <% if aluno.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <%= form.fields_for :endereco do |endereco_form| %>
    <div>
      <%= endereco_form.label :logradouro, display: "block" %>
      <%= endereco_form.text_field :logradouro %>
    </div>

    <div>
      <%= endereco_form.label :cep, display: "block" %>
      <%= endereco_form.text_field :cep %>
    </div>

  <%end %>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :data_nascimento, style: "display: block" %>
    <%= form.date_field :data_nascimento %>
  </div>

  <div>
    <%= form.label :contato, style: "display: block" %>
    <%= form.text_field :contato %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.password_field :senha %>
  </div>

  <%= form.label :academium_id, "Academia", style: "display: block" %>
  <%= form.select :academium_id, @academias, {}, { class: "form-select" } %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Show this aluno", @aluno %> |
  <%= link_to "Back to alunos", alunos_path %>
</div>

app/views/alunos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Alunos</h1>

  <%= link_to "Voltar para a home", "/" %>


  <div id="alunos">
  <% @alunos.each do |aluno| %>
    <%= render aluno %>
    <p>
      <%= link_to "Show this aluno", aluno %>
    </p>
  <% end %>
</div>

  <br>
<%= link_to "Novo aluno", new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Voltar para a home", "/" %>
</div>

app/views/alunos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aluno %>

<div>
  <%= link_to "Editar", edit_aluno_path(@aluno) %> |
  <%= link_to "Voltar para todos os alunos", alunos_path %>

  <%= button_to "Deletar", @aluno, method: :delete %>
</div>