config/routes.rb
Rails.application.routes.draw do
  resources :exercicios
  resources :instrutors
  resources :academia
  resources :alunos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :proprietarios, :controllers => {:registrations => "registrations"}

end

app/models/instrutor.rb
class Instrutor < ApplicationRecord
  belongs_to :academium

  has_one :endereco, dependent: :destroy
  accepts_nested_attributes_for :endereco, allow_destroy: true

  validates :nome, presence: true, length: { maximum: 100, minimum: 10 }, format: { with: /\A[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+\z/, message: "Somente letras"}
  validates :cpf, presence: true, length: { is: 11 }, uniqueness: true, format: { with: /\A[0-9]+\z/, message: "Somente números" }
  validates :data_de_nascimento, presence: true, comparison: {less_than: Time.zone.today, greater_than: Date.new(1850, 1, 1)}
  validates :contato_telefone, presence: true, length: { is: 11 }, format: { with: /\A[0-9]+\z/, message: "Somente números" }
  validates :horas_de_trabalho, presence: true
  validates :academium_id, presence: true
  validates :email , presence: true, length: { maximum: 100, minimum: 5 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "E-mail inválido"}
  validates :password , presence: true, length: { maximum: 20, minimum: 6 }
end

app/controllers/instrutors_controller.rb
class InstrutorsController < ApplicationController
  before_action :set_instrutor, only: %i[ show edit update destroy ]

  # GET /instrutors or /instrutors.json
  def index
    @instrutors = Instrutor.all
  end

  # GET /instrutors/1 or /instrutors/1.json
  def show
  end

  # GET /instrutors/new
  def new
    @instrutor = Instrutor.new
    @academias = Academium.all.map { |acad| ["#{acad.id} - #{acad.nome}", acad.id] }
    @instrutor.build_endereco
  end

  # GET /instrutors/1/edit
  def edit
    @academias = Academium.all.map { |acad| ["#{acad.id} - #{acad.nome}", acad.id] }
  end

  # POST /instrutors or /instrutors.json
  def create
    @instrutor = Instrutor.new(instrutor_params)
    @academias = Academium.all.map { |acad| ["#{acad.id} - #{acad.nome}", acad.id] }
    @instrutor.endereco = Endereco.new(instrutor_params[:endereco_attributes])

    respond_to do |format|
      if @instrutor.save
        format.html { redirect_to instrutor_url(@instrutor), notice: "Instrutor was successfully created." }
        format.json { render :show, status: :created, location: @instrutor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instrutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instrutors/1 or /instrutors/1.json
  def update
    @academias = Academium.all.map { |acad| ["#{acad.id} - #{acad.nome}", acad.id] }

    respond_to do |format|
      if @instrutor.update(instrutor_params)
        format.html { redirect_to instrutor_url(@instrutor), notice: "Instrutor was successfully updated." }
        format.json { render :show, status: :ok, location: @instrutor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instrutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instrutors/1 or /instrutors/1.json
  def destroy
    @instrutor.destroy

    respond_to do |format|
      format.html { redirect_to instrutors_url, notice: "Instrutor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrutor
      @instrutor = Instrutor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instrutor_params
      params.require(:instrutor).permit(:nome, :cpf, :data_de_nascimento, :contato_telefone, :academium_id, :horas_de_trabalho, :email, :password,
                                        endereco_attributes: [:logradouro, :cep])
    end
end

app/helpers/instrutors_helper.rb
module InstrutorsHelper
end

app/views/instrutors/_form.html.erb
<%= form_with(model: instrutor) do |form| %>
  <% if instrutor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(instrutor.errors.count, "error") %> prohibited this instrutor from being saved:</h2>

      <ul>
        <% instrutor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>

  <div>
    <%= form.label :contato_telefone, style: "display: block" %>
    <%= form.text_field :contato_telefone %>
  </div>

  <%= form.fields_for :endereco do |endereco_form| %>
    <div>
      <%= endereco_form.label :logradouro, display: "block" %>
      <%= endereco_form.text_field :logradouro %>
    </div>

    <div>
      <%= endereco_form.label :cep, display: "block" %>
      <%= endereco_form.text_field :cep %>
    </div>

  <%end %>

  <div class="col-md-6 form-group">
    <%= form.label :academium_id, "Academia", style: "display: block" %>
    <%= form.select :academium_id, options_for_select(Academium.all.ids) %>
  </div>

  <div>
    <%= form.label :horas_de_trabalho, style: "display: block" %>
    <%= form.time_field :horas_de_trabalho %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/instrutors/_instrutor.html.erb
<div id="<%= dom_id instrutor %>">
  <p>
    <strong>Nome:</strong>
    <%= instrutor.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= instrutor.cpf %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= instrutor.data_de_nascimento %>
  </p>

  <p>
    <strong>Contato:</strong>
    <%= instrutor.contato_telefone %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= instrutor.endereco.logradouro %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= instrutor.endereco.cep %>
  </p>

  <p>
    <strong>Academium:</strong>
    <%= instrutor.academium.nome %>
  </p>

  <p>
    <strong>Horas de trabalho:</strong>
    <%= instrutor.horas_de_trabalho %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= instrutor.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= instrutor.password %>
  </p>

</div>

app/views/instrutors/edit.html.erb
<h1>Editing instrutor</h1>

<%= render "form", instrutor: @instrutor %>

<br>

<div>
  <%= link_to "Show this instrutor", @instrutor %> |
  <%= link_to "Back to instrutors", instrutors_path %>
</div>

app/views/instrutors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Instrutors</h1>

<%= link_to "Voltar para a home", "/" %>

<div id="instrutors">
  <% @instrutors.each do |instrutor| %>
    <%= render instrutor %>
    <p>
      <%= link_to "Show this instrutor", instrutor %>
    </p>
  <% end %>
</div>

<br>

<%= link_to "Novo instrutor", new_instrutor_path %>

app/views/instrutors/new.html.erb
<h1>New instrutor</h1>

<%= render "form", instrutor: @instrutor %>

<br>

<div>
  <%= link_to "Voltar para a home", "/" %>
</div>

app/views/instrutors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @instrutor %>

<div>
  <%= link_to "Editar", edit_instrutor_path(@instrutor) %> |
  <%= link_to "Voltar para todos os instrutores", instrutors_path %>

  <%= link_to "Adicionar novo aluno" "/alunos/new" %>

  <%= button_to "Deletar instrutor", @instrutor, method: :delete %>
</div>